### PR TITLE
Modify build scripts to enable installation on Amazon Linux

### LINKED ISSUE #90: Need support for Amazon Linux
Amazon AWS has a set of supported Amazon Machine Images (AMI). "Amazon Linux" is a commonly used AMI. Amazon Linux defines the OS version within the /etc/system-release file which ,as example, currently contains "Amazon Linux release 2 (Karoo)" for the Amazon Linux  AMI. 

Currently the HIRS RPMs are  looking for similar files (e.g. /etc/rehat-release) but will not install properly on Amazon Linux. Adding a /etc/redhat-release file in the AWS instance will fix the problem for that install. To support Amazon linux a check for the /etc/system-release file should be put in the install scripts if /etc/redhat is not found.

### PR DESCRIPTION
**Pull request by chubtub**
Modified the build scripts to parse the Amazon Linux version as appropriate.  Default behavior is to treat version 2 the same as RHEL7.

Closes #90

### CODE REVIEW

**Comment by apldev3** [comment]
This looks good to me. Has this been tested on an AWS image?

**Comment by apldev3** [comment]
Hey @mtsai1 just a headsup that I created a Docker Image to test the packaging on Amazon Linux and it's not working properly. It does fine right up until it needs to build HIRS_ProvisionerTPM2 and then it gets a little wonky.

Best I can reason is that `make` is just a little bit different on the Amazon Linux container compared to basic CentOS or RHEL. When I get the container to just do a CMake I can go in and `make` everything it generated just fine, but if I try to do `make` from within the Amazon Linux container it appears to not be linking the libraries properly. Will need to do additional exploration of this issue to figure out the difference and account for it in the `CMakeLists.txt`.

**Comment by mtsai1** [comment]
This issue was raised to address the centos packaging script printing an error message because it could not detect the centos version.  The changes resolve packaging errors and generate rpms that are successfully installed on Amazon Linux.  The cmake errors should be addressed in a separate issue.

**Comment by apldev3** [comment]
Alright, that's fair, we can set that up.

**Comment by apldev3** [comment]
@mtsai1 I went ahead and commented out that build step, but left it in with a TODO that can be addressed in a separate issue.

**Comment by apldev3** [comment]
Issue #102 created to track the building/packaging issue on Amazon Linux. For the mean time the installation of the RPM should work per this ticket.

**Comment by apldev3** [comment]
I'll leave it to @iadgovuser26 to verify that this works for their needs.

**Comment by apldev3** [comment]
@iadgovuser26 same question as in the other ticket. Are we good here?

**Pull request merged**
