### PR TITLE
[#1] Add support for processing ECC certificates as part of the trust chain

### LINKED ISSUE #1: ACA Import Trust Chain CA Certificates needs to support ECC based certificates.
Even though the current version of the ACA only supports RSA public key based EK certs, TPM manufacturers can use Ecc keys to sign RSA public keys within an EK certs. Specifically Nuvoton_TPM_Root_CA_2110.cer is an ECC based certificate which is used to validate some Nuvoton produced RSA based EK certs. 
```
EK cert:
Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
Signature Algorithm: ecdsa-with-SHA256
```
The ACA should be able to upload an Ecc based intermediate or root Trust Chain CA Certificate. Furthermore the ACA should be able to validate and use the ECC based certs to validate the Certificate chain of any EK certificate.

### PR DESCRIPTION
**Pull request by apldev3**
This is a small merge request to allow for uploading of ECC certificate to the AttestationCA Portal.

Closes #1

### CODE REVIEW

**Comment by iadgovuser26** [comment]
Tested with  Nuvaton TPM Model NPCT6xx using the Nuvoton TPM Root CA 2110 with all policies enabled. Worked!

**Comment by apldev4** [comment]
The `publicKeyModulusHexValue` field of `Certificate` is never used anywhere. I'd rather remove it than set it to null. Setting variables to null because there is not a clear use for them is asking for trouble. The fact that `Certificate.getPublicKeyModulus()` can now return a null won't cause a NullPointerException until someone passes an ECC Endorsement Credential as part of their identity request.

**Comment by apldev3** [comment]
@apldev4 there's actually a somewhat indirect use for them if you poke around a bit. The field is used in `CertificateSelector` as part of the 1.2 provisioning process in the ACA.

**Comment by apldev4** [comment]
> @apldev4 there's actually a somewhat indirect use for them if you poke around a bit. The field is used in `CertificateSelector` as part of the 1.2 provisioning process in the ACA. Trust me, I wanted to remove the field, but it appears to be a rather integral part of the original provisioning.

Good call. Looks good to me, then.

**Comment by apldev3** [comment]
Got two thumbs up, merging in now.

**Pull request merged**
