### PR TITLE
 [#847] Update HIRS Attestation CA and HIRS Attestation CA Portal Checkstyles.

### PR DESCRIPTION
**Pull request by ThatSilentCoder**
### Description:
[Checkstyle](https://github.com/checkstyle/checkstyle/tree/master) is used for meeting best practices for java code styling. All classes in HIRS_AttestationCA and HIRS_AttestationCAPortal should be updated to pass checkstyle tests being run by gradle.

### How I Got Rid Of The Checkstyle Errors:
1. I ran the `./gradlew clean HIRS_AttestationCA:check --rerun-tasks` in the terminal window of my IDE. 
2. Because there were roughly 500-600 checkstyle errors, it was very difficult to scroll up and down the terminal window. So to make the process of reducing the errors easier, I had to write the output of the command into a another file.
3. I created a file called checkstyles_errors.txt using `touch checkstyles_errors.txt`.
4. Then I ran the gradle command and appended the output to the "end" of the new file, like so:
`./gradlew clean HIRS_AttestationCA:check --rerun-tasks  >  checkstyles_errors.txt  2>&1`
5. Since I wanted to keep an accurate count of how many checkstyle errors I encountered every time I ran this command, I would then run the following command: `grep -c "WARN" checkstyles_errors.txt`
6. These two commands allowed me to view the errors and keep track of how many errors were left.

### Test Instructions:
1. Follow steps 1 - 3 in this previous pull request: [issue #844 ](https://github.com/nsacyber/HIRS/pull/846) to confirm you can save and apply checkstyle recommended styling changes to your code in your favorite IDE.
7. Run the command below to confirm that all the checkstyle errors for the HIRS_AttestationCA module have been fixed (there were approximately 500 checkstyle errors in this module):
`./gradlew clean HIRS_AttestationCA:check --rerun-tasks`
8. Run the command below to confirm that that all the The HIRS_AttestationCAPortal module have been fixed (there were approximately 100 checkstyle errors in this module):
`./gradlew clean HIRS_AttestationCAPortal:check --rerun-tasks`
9.Run the command below to confirm that there are no issues building or running tests for the entire application:
`./gradlew clean build --rerun-tasks`
10. If you were able to run all three commands without running into any issues, you have successfully verified that the checkstyles guidelines have been applied to the these two modules successfully.

### Issues this PR addresses:
Closes issue #847

### CODE REVIEW

**Review by chubtub — COMMENTED** [review]
All three ./gradlew commands in the test instructions were successful, but also gave me the same following warnings:
> Task :HIRS_AttestationCA:compileJava
/home/matsai/HIRS/HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/rim/EventLogMeasurements.java:30: warning: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
@EqualsAndHashCode
^
/home/matsai/HIRS/HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/record/TPMMeasurementRecord.java:29: warning: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
@EqualsAndHashCode
^
/home/matsai/HIRS/HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/IDevIDCertificate.java:31: warning: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
@EqualsAndHashCode

**Comment by ThatSilentCoder** [comment]
> All three ./gradlew commands in the test instructions were successful, but also gave me the same following warnings, are these expected?
> 
> > Task :HIRS_AttestationCA:compileJava
> > /home/matsai/HIRS/HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/rim/EventLogMeasurements.java:30: warning: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
> > @EqualsAndHashCode
> > ^
> > /home/matsai/HIRS/HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/record/TPMMeasurementRecord.java:29: warning: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
> > @EqualsAndHashCode
> > ^
> > /home/matsai/HIRS/HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/IDevIDCertificate.java:31: warning: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
> > @EqualsAndHashCode

I got those same messages when I built the entire module. To be quite honest,  don't know how to address these warnings. I'm aware of the fact that there are multiple POJOS, throughout the codebase, where the @EqualsAndHashCode annotation does not call the POJO's super class; however I do not know whether or not we want the annotation that is in these three classes to make a call to the super's Equals and Hash code methods.

**Comment by chubtub** [comment]
> > All three ./gradlew commands in the test instructions were successful, but also gave me the same following warnings, are these expected?
> > > Task :HIRS_AttestationCA:compileJava
> > > /home/matsai/HIRS/HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/rim/EventLogMeasurements.java:30: warning: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
> > > @EqualsAndHashCode
> > > ^
> > > /home/matsai/HIRS/HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/record/TPMMeasurementRecord.java:29: warning: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
> > > @EqualsAndHashCode
> > > ^
> > > /home/matsai/HIRS/HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/IDevIDCertificate.java:31: warning: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
> > > @EqualsAndHashCode
> 
> I got those same messages when I built the entire module. To be quite honest, I don't know how to address these warnings. I'm aware of the fact that there are multiple POJOS, throughout the codebase, where the @EqualsAndHashCode annotation does not call the POJO's super class; however I do not know whether or not we want the annotation, that is in these three classes, to make a call to the super class' Equals and Hash code methods.

These are my thoughts:
- EventLogMeasurement - @EqualsAndHashCode(callSuper = false); super class is SupportRimManifest, SupportRimManifest.equals() calls super.equals().  I'm not sure how this would fit into use cases of EventLogMeasurement.equals().
- TpmMeasurementRecord - @EqualsAndHashCode(callSuper = false); super class is ExaminableRecord which does not override its equals() and hashCode() methods.
- IDevIdCertificate - @EqualsAndHashCode(callSuper = true); super class is Certificate which overrides its inherited equals() and hashCode(). Certificate.equals() compares on class type then array comparison, Certificate.hashCode() returns a hash of the byte values.

**Comment by ThatSilentCoder** [comment]
> > > All three ./gradlew commands in the test instructions were successful, but also gave me the same following warnings, are these expected?
> > > > Task :HIRS_AttestationCA:compileJava
> > > > /home/matsai/HIRS/HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/rim/EventLogMeasurements.java:30: warning: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
> > > > @EqualsAndHashCode
> > > > ^
> > > > /home/matsai/HIRS/HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/record/TPMMeasurementRecord.java:29: warning: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
> > > > @EqualsAndHashCode
> > > > ^
> > > > /home/matsai/HIRS/HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/IDevIDCertificate.java:31: warning: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
> > > > @EqualsAndHashCode
> > 
> > 
> > I got those same messages when I built the entire module. To be quite honest, I don't know how to address these warnings. I'm aware of the fact that there are multiple POJOS, throughout the codebase, where the @EqualsAndHashCode annotation does not call the POJO's super class; however I do not know whether or not we want the annotation, that is in these three classes, to make a call to the super class' Equals and Hash code methods.
> 
> These are my thoughts:
> 
> * EventLogMeasurement - @EqualsAndHashCode(callSuper = false); super class is SupportRimManifest, SupportRimManifest.equals() calls super.equals().  I'm not sure how this would fit into use cases of EventLogMeasurement.equals().
> * TpmMeasurementRecord - @EqualsAndHashCode(callSuper = false); super class is ExaminableRecord which does not override its equals() and hashCode() methods.
> * IDevIdCertificate - @EqualsAndHashCode(callSuper = true); super class is Certificate which overrides its inherited equals() and hashCode(). Certificate.equals() compares on class type then array comparison, Certificate.hashCode() returns a hash of the byte values.

I applied the suggested changes to the code.

**Review by chubtub — APPROVED** [review]
Changes look good

**Pull request merged**
